# Generated by Django 6.0.1 on 2026-01-10 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizer',
            new_name='Organization',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
